# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Customizable Docker Buildx Build
      uses: zmingxie/docker_buildx@v1.1
      with:
        # Tags (comma separated) to apply to the image
        tag: latest
        # Name of the image
        imageName: hades32/prometheus-speedtest
        # Indicate if the builded image should be published on Docker HUB
        publish: true
        # Platforms (comma separated) that should be used to build the image
        platform: linux/amd64,linux/arm64,linux/arm/v7
        # User that will publish the image, if indicated
        dockerHubUser: hades32
        # Password of the dockerHubUser
        dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
